### ISSUE TITLE
AVR?

### ISSUE THREAD

**Issue by FrankBoesing** [dherrendoerfer/microme#1]
AVR

Doesn't the communtication with the AVR need more time than a simple digitalReadFast/digitalWriteFast ?
What's the reason for the AVR?

And..would'nt the Teensy 3.6 be better? Overclocked 256MHz...

**Comment by dherrendoerfer** [comment]
The AVR is just a plain, cheap IO controller for whatever, it handles keyboard input, will get several modes for that, handle keymaps, and do some I/O via a 25pin SUBD connector, It's 5V safe and cheap to replace.
The direct IOs would be way faster, but this way the IO is separated, and can make use of the serial buffers for transmitting short messages. 

Yes, the Teensy 3.6 would be a lot better - so it's a valid upgrade path - also, the Teensy 3.2 for simple audio sits in a full size 3.6 socket - so that could be updated as well. ;-)

Unfortunately - the boards that were on the way here did not make it past the import/tax/customs office in Germany. So I need to wait a bit more to give them a shake-down.

**Comment by dherrendoerfer** [comment]
The boards are in, somewhat working (need rework) and the 3 controllers are happily communicating. 
Would you like to have one ?
